FROM golang:1.23 as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server cmd/server/main.go


FROM alpine:latest

ENV PORT=8080

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /server /server

EXPOSE 8080

CMD ["/server"]